In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

bmw_sales_data = pd.read_csv('../../../datasets/BMW sales data (2010-2024).csv')
bmw_sales_data

,Model,Year,Region,Color,Fuel_Type,Transmission,Engine_Size_L,Mileage_KM,Price_USD,Sales_Volume,Sales_Classification
0,5 Series,2016,Asia,Red,Petrol,Manual,3.5,151748,98740,8300,High
1,i8,2013,North America,Red,Hybrid,Automatic,1.6,121671,79219,3428,Low
2,5 Series,2022,North America,Blue,Petrol,Automatic,4.5,10991,113265,6994,Low
3,X3,2024,Middle East,Blue,Petrol,Automatic,1.7,27255,60971,4047,Low
4,7 Series,2020,South America,Black,Diesel,Manual,2.1,122131,49898,3080,Low
...,...,...,...,...,...,...,...,...,...,...,...
49995,i3,2014,Asia,Red,Hybrid,Manual,4.6,151030,42932,8182,High
49996,i3,2023,Middle East,Silver,Electric,Manual,4.2,147396,48714,9816,High
49997,5 Series,2010,Middle East,Red,Petrol,Automatic,4.5,174939,46126,8280,High
49998,i3,2020,Asia,White,Electric,Automatic,3.8,3379,58566,9486,High
49999,X1,2020,North America,Blue,Diesel,Manual,3.3,171003,77492,1764,Low

In [4]:
X = bmw_sales_data.copy()
y = X['Sales_Volume']
X.drop(columns=['Sales_Volume'], inplace = True)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    train_size=0.6,
    random_state=42
)

X_test, X_val, y_test, y_val = train_test_split(
    X_test,
    y_test,
    train_size=0.5,
    random_state=42
)
bmw_train_data_set = pd.concat([X_train, y_train], axis=1)
bmw_train_data_set

,Model,Year,Region,Color,Fuel_Type,Transmission,Engine_Size_L,Mileage_KM,Price_USD,Sales_Classification,Sales_Volume
18306,X3,2013,Asia,Silver,Hybrid,Manual,2.6,140438,41743,Low,3710
49528,5 Series,2014,Europe,Black,Electric,Manual,4.4,82749,112481,Low,6119
44745,3 Series,2011,Middle East,Red,Hybrid,Manual,3.9,168621,89312,Low,6500
46827,X3,2011,Africa,Blue,Hybrid,Manual,3.7,2885,113776,High,8321
27531,7 Series,2021,Middle East,Grey,Electric,Manual,4.7,130807,88939,Low,6878
...,...,...,...,...,...,...,...,...,...,...,...
11284,X5,2011,Africa,Grey,Electric,Automatic,4.1,6967,54853,High,8008
44732,M5,2016,South America,Black,Petrol,Manual,1.9,150464,30430,Low,3373
38158,X6,2019,Asia,Red,Electric,Automatic,3.3,142419,119997,Low,4575
860,X6,2018,North America,Grey,Diesel,Automatic,4.0,110555,107478,Low,5061
15795,i8,2019,South America,Black,Petrol,Manual,4.7,41614,83121,Low,5903

In [7]:
bmw_sales_volume_year_model = bmw_train_data_set.groupby(by=['Year', 'Model']).Sales_Volume.mean().reset_index()
bmw_sales_volume_year_model

     Year     Model  Sales_Volume
0    2010  3 Series   5095.189744
1    2010  5 Series   5076.196721
2    2010  7 Series   5004.905882
3    2010        M3   5130.121387
4    2010        M5   5237.946809
..    ...       ...           ...
160  2024        X3   5071.654639
161  2024        X5   5028.748387
162  2024        X6   5228.551220
163  2024        i3   4919.802139
164  2024        i8   5316.941176

[165 rows x 3 columns]